version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow/mlruns
    environment:
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=*
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlruns/mlflow.db
      --artifacts-destination /mlflow/mlruns
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
    networks:
      - astro_network

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - astro_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mlflow_data:
  redis_data:

networks:
  astro_network:
    external: true
    name: ecommerce-customer-churn--prediction-mlops-pipeline_43bb99_airflow